# Official R runtime
FROM r-base

# Copy the current directory contents into /myscripts 
COPY . /usr/local/src/myscripts

# Set the working directory to /myscripts
WORKDIR /usr/local/src/myscripts

# Uncomment and update the line below for Rscripts
# CMD ["Rscript", "myscript.R"]